services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gal
      POSTGRES_PASSWORD: lag
      POSTGRES_DB: db
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 0
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
    command: postgres -c max_connections=100 -c shared_buffers=256MB -c effective_cache_size=768MB -c maintenance_work_mem=64MB -c checkpoint_completion_target=0.9 -c wal_buffers=7864kB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=5242kB -c min_wal_size=1GB -c max_wal_size=4GB -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c log_min_duration_statement=0 -c log_statement=all -c log_connections=on -c log_disconnections=on -c client_min_messages=notice
volumes:
  db: ~
