/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./schema/context"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  EnumRatingFieldUpdateOperationsInput: { // input type
    set?: NexusGenEnums['Rating'] | null; // Rating
  }
  EnumRatingFilter: { // input type
    equals?: NexusGenEnums['Rating'] | null; // Rating
    in?: NexusGenEnums['Rating'][] | null; // [Rating!]
    not?: NexusGenInputs['NestedEnumRatingFilter'] | null; // NestedEnumRatingFilter
    notIn?: NexusGenEnums['Rating'][] | null; // [Rating!]
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedEnumRatingFilter: { // input type
    equals?: NexusGenEnums['Rating'] | null; // Rating
    in?: NexusGenEnums['Rating'][] | null; // [Rating!]
    not?: NexusGenInputs['NestedEnumRatingFilter'] | null; // NestedEnumRatingFilter
    notIn?: NexusGenEnums['Rating'][] | null; // [Rating!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  PostCreateInput: { // input type
    body: string; // String!
    rating: NexusGenEnums['Rating']; // Rating!
    shop: NexusGenInputs['ShopConnectNestedOne']; // ShopConnectNestedOne!
    subtitle: string; // String!
    thumbnail: string; // String!
    title: string; // String!
  }
  PostCreateManyShopInput: { // input type
    body: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    rating: NexusGenEnums['Rating']; // Rating!
    subtitle: string; // String!
    thumbnail?: string | null; // String
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostCreateManyShopInputEnvelope: { // input type
    data?: NexusGenInputs['PostCreateManyShopInput'][] | null; // [PostCreateManyShopInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  PostCreateNestedManyWithoutShopInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutShopInput'][] | null; // [PostCreateOrConnectWithoutShopInput!]
    create?: NexusGenInputs['PostCreateWithoutShopInput'][] | null; // [PostCreateWithoutShopInput!]
    createMany?: NexusGenInputs['PostCreateManyShopInputEnvelope'] | null; // PostCreateManyShopInputEnvelope
  }
  PostCreateOrConnectWithoutShopInput: { // input type
    create: NexusGenInputs['PostCreateWithoutShopInput']; // PostCreateWithoutShopInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateWithoutShopInput: { // input type
    body: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    rating: NexusGenEnums['Rating']; // Rating!
    subtitle: string; // String!
    thumbnail?: string | null; // String
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostScalarWhereInput: { // input type
    AND?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    NOT?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    OR?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    body?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    rating?: NexusGenInputs['EnumRatingFilter'] | null; // EnumRatingFilter
    shopId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    subtitle?: NexusGenInputs['StringFilter'] | null; // StringFilter
    thumbnail?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  PostUpdateInput: { // input type
    body?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    rating?: NexusGenInputs['EnumRatingFieldUpdateOperationsInput'] | null; // EnumRatingFieldUpdateOperationsInput
    shop?: NexusGenInputs['ShopUpdateOneRequiredWithoutPostsInput'] | null; // ShopUpdateOneRequiredWithoutPostsInput
    subtitle?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    thumbnail?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUpdateManyMutationInput: { // input type
    body?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    rating?: NexusGenInputs['EnumRatingFieldUpdateOperationsInput'] | null; // EnumRatingFieldUpdateOperationsInput
    subtitle?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    thumbnail?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUpdateManyWithWhereWithoutShopInput: { // input type
    data: NexusGenInputs['PostUpdateManyMutationInput']; // PostUpdateManyMutationInput!
    where: NexusGenInputs['PostScalarWhereInput']; // PostScalarWhereInput!
  }
  PostUpdateManyWithoutShopInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutShopInput'][] | null; // [PostCreateOrConnectWithoutShopInput!]
    create?: NexusGenInputs['PostCreateWithoutShopInput'][] | null; // [PostCreateWithoutShopInput!]
    createMany?: NexusGenInputs['PostCreateManyShopInputEnvelope'] | null; // PostCreateManyShopInputEnvelope
    delete?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    deleteMany?: NexusGenInputs['PostScalarWhereInput'][] | null; // [PostScalarWhereInput!]
    disconnect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    set?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    update?: NexusGenInputs['PostUpdateWithWhereUniqueWithoutShopInput'][] | null; // [PostUpdateWithWhereUniqueWithoutShopInput!]
    updateMany?: NexusGenInputs['PostUpdateManyWithWhereWithoutShopInput'][] | null; // [PostUpdateManyWithWhereWithoutShopInput!]
    upsert?: NexusGenInputs['PostUpsertWithWhereUniqueWithoutShopInput'][] | null; // [PostUpsertWithWhereUniqueWithoutShopInput!]
  }
  PostUpdateWithWhereUniqueWithoutShopInput: { // input type
    data: NexusGenInputs['PostUpdateWithoutShopInput']; // PostUpdateWithoutShopInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostUpdateWithoutShopInput: { // input type
    body?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    rating?: NexusGenInputs['EnumRatingFieldUpdateOperationsInput'] | null; // EnumRatingFieldUpdateOperationsInput
    subtitle?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    thumbnail?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  PostUpsertWithWhereUniqueWithoutShopInput: { // input type
    create: NexusGenInputs['PostCreateWithoutShopInput']; // PostCreateWithoutShopInput!
    update: NexusGenInputs['PostUpdateWithoutShopInput']; // PostUpdateWithoutShopInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  QueryPostsOrderByInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ShopConnectNestedOne: { // input type
    connect: NexusGenInputs['ShopWhereUniqueInput']; // ShopWhereUniqueInput!
  }
  ShopCreateInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name: string; // String!
    posts?: NexusGenInputs['PostCreateNestedManyWithoutShopInput'] | null; // PostCreateNestedManyWithoutShopInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ShopCreateOrConnectWithoutPostsInput: { // input type
    create: NexusGenInputs['ShopCreateWithoutPostsInput']; // ShopCreateWithoutPostsInput!
    where: NexusGenInputs['ShopWhereUniqueInput']; // ShopWhereUniqueInput!
  }
  ShopCreateWithoutPostsInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ShopUpdateInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    posts?: NexusGenInputs['PostUpdateManyWithoutShopInput'] | null; // PostUpdateManyWithoutShopInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  ShopUpdateOneRequiredWithoutPostsInput: { // input type
    connect?: NexusGenInputs['ShopWhereUniqueInput'] | null; // ShopWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ShopCreateOrConnectWithoutPostsInput'] | null; // ShopCreateOrConnectWithoutPostsInput
    create?: NexusGenInputs['ShopCreateWithoutPostsInput'] | null; // ShopCreateWithoutPostsInput
    update?: NexusGenInputs['ShopUpdateWithoutPostsInput'] | null; // ShopUpdateWithoutPostsInput
    upsert?: NexusGenInputs['ShopUpsertWithoutPostsInput'] | null; // ShopUpsertWithoutPostsInput
  }
  ShopUpdateWithoutPostsInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    id?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  ShopUpsertWithoutPostsInput: { // input type
    create: NexusGenInputs['ShopCreateWithoutPostsInput']; // ShopCreateWithoutPostsInput!
    update: NexusGenInputs['ShopUpdateWithoutPostsInput']; // ShopUpdateWithoutPostsInput!
  }
  ShopWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  Rating: "BAD" | "GOOD" | "OK"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Mutation: {};
  Post: { // root type
    body: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    rating: NexusGenEnums['Rating']; // Rating!
    shopId: string; // String!
    subtitle: string; // String!
    thumbnail?: string | null; // String
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Query: {};
  Shop: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createOnePost: NexusGenRootTypes['Post']; // Post!
    createOneShop: NexusGenRootTypes['Shop']; // Shop!
    deleteOneShop: NexusGenRootTypes['Shop'] | null; // Shop
    updateOnePost: NexusGenRootTypes['Post'] | null; // Post
    updateOneShop: NexusGenRootTypes['Shop'] | null; // Shop
  }
  Post: { // field return type
    body: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    rating: NexusGenEnums['Rating']; // Rating!
    shop: NexusGenRootTypes['Shop']; // Shop!
    shopId: string; // String!
    subtitle: string; // String!
    thumbnail: string | null; // String
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Query: { // field return type
    post: NexusGenRootTypes['Post'] | null; // Post
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    shop: NexusGenRootTypes['Shop'] | null; // Shop
    shops: NexusGenRootTypes['Shop'][]; // [Shop!]!
  }
  Shop: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    name: string; // String!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    createOnePost: 'Post'
    createOneShop: 'Shop'
    deleteOneShop: 'Shop'
    updateOnePost: 'Post'
    updateOneShop: 'Shop'
  }
  Post: { // field return type name
    body: 'String'
    createdAt: 'DateTime'
    id: 'String'
    rating: 'Rating'
    shop: 'Shop'
    shopId: 'String'
    subtitle: 'String'
    thumbnail: 'String'
    title: 'String'
    updatedAt: 'DateTime'
  }
  Query: { // field return type name
    post: 'Post'
    posts: 'Post'
    shop: 'Shop'
    shops: 'Shop'
  }
  Shop: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    name: 'String'
    posts: 'Post'
    updatedAt: 'DateTime'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOnePost: { // args
      data: NexusGenInputs['PostCreateInput']; // PostCreateInput!
    }
    createOneShop: { // args
      data: NexusGenInputs['ShopCreateInput']; // ShopCreateInput!
    }
    deleteOneShop: { // args
      where: NexusGenInputs['ShopWhereUniqueInput']; // ShopWhereUniqueInput!
    }
    updateOnePost: { // args
      data: NexusGenInputs['PostUpdateInput']; // PostUpdateInput!
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    updateOneShop: { // args
      data: NexusGenInputs['ShopUpdateInput']; // ShopUpdateInput!
      where: NexusGenInputs['ShopWhereUniqueInput']; // ShopWhereUniqueInput!
    }
  }
  Query: {
    post: { // args
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['QueryPostsOrderByInput'][] | null; // [QueryPostsOrderByInput!]
    }
    shop: { // args
      where: NexusGenInputs['ShopWhereUniqueInput']; // ShopWhereUniqueInput!
    }
    shops: { // args
      after?: NexusGenInputs['ShopWhereUniqueInput'] | null; // ShopWhereUniqueInput
      before?: NexusGenInputs['ShopWhereUniqueInput'] | null; // ShopWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Shop: {
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}